# This is a basic workflow to help you get started with Actions

name: trans

# Controls when the workflow will run
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.11"]    
          # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: get sdr from fvtt5e
        run: wget https://github.com/foundryvtt/dnd5e/raw//master/packs/monsters.db -O ./en-db/sdr.db
      - name: Add & Commit1
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: "./en-db/sdr.db"
          branch: main
      # Runs a single command using the runners shell
      - name: translate from db
        run: |
           python3 /home/runner/work/classpack-expansion/classpack-expansion/.github/trans_en2en.py
      - name: translate to db
        run: |
           python3 /home/runner/work/classpack-expansion/classpack-expansion/.github/trans_zh2zh.py
      - name: Add & Commit2
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: "/json/*"
          branch: main
