# This is a basic workflow to help you get started with Actions

name: get-reource

# Controls when the workflow will run
on:
  schedule:
    - cron:  '00 00 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.10"]    
          # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: get 5etool resource
        run: for i in `cat ./.github/workflows/bestiary-list.txt`;do wget https://raw.githubusercontent.com/5etools-mirror-1/5etools-mirror-1.github.io/master/data/bestiary/${i} -O ./en-json;done
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: "./en-json"
          branch: main
